- name: Check if repo directory exists
  stat:
    path: '/opt/previews/bublik-pr{{ pr_id }}/repo'
  register: repo_dir_check

- name: Check if compose files exist
  stat:
    path: '/opt/previews/bublik-pr{{ pr_id }}/repo/docker-compose.yml'
  register: compose_file_check
  when: repo_dir_check.stat.exists

- name: Remove Compose Containers
  community.docker.docker_compose_v2:
    project_src: /opt/previews/bublik-pr{{ pr_id }}/repo
    state: absent
    files:
      - docker-compose.yml
      - docker-compose.db.yml
    remove_volumes: true
  become_user: '{{ bublik_user }}'
  when:
    - repo_dir_check.stat.exists
    - compose_file_check.stat.exists | default(false)
  ignore_errors: true

- name: Delete Preview Directory
  file:
    path: '/opt/previews/bublik-pr{{ pr_id }}'
    state: absent

- name: Remove Proxy Domain
  file:
    path: '/opt/traefik/dynamic/pr-{{ pr_id }}-preview.yml'
    state: absent
  become_user: '{{ bublik_user }}'
