services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NGINX_PORT: ${NGINX_PORT:-80}
      URL_PREFIX: ${URL_PREFIX}
    ports:
      - '4200:${NGINX_PORT:-80}'
    expose:
      - '4200'
    volumes:
      - static_data:/app/bublik/bublik/representation/static
    networks:
      - bublik_net

volumes:
  static_data:
    external: true

networks:
  bublik_net:
    external: true
