name: Deploy PR Preview

on:
  workflow_dispatch:
    inputs:
      pr_id:
        description: 'PR ID to deploy'
        required: true
        default: '1'

      frontend_branch:
        description: 'Frontend branch'
        required: false
        default: 'main'

      backend_branch:
        description: 'Backend branch'
        required: false
        default: 'main'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    environment:
      name: pr-${{ github.event.pull_request.number || github.event.inputs.pr_id }}
      url: https://pr-${{ github.event.pull_request.number || github.event.inputs.pr_id }}.${{ vars.TRAEFIK_DOMAIN }}

    concurrency:
      group: deploy-preview-${{ github.event.pull_request.number || github.event.inputs.pr_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        env:
          RUNNER_TOOL_CACHE: ${{ github.workspace }}/_work/_tool
          AGENT_TOOLSDIRECTORY: ${{ github.workspace }}/_work/_tool
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Ansible requirements
        run: ansible-galaxy install -r ansible/requirements.yml

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/preview
          chmod 600 ~/.ssh/preview
          ssh-keyscan -H ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts

      - name: Generate Ansible inventory
        run: |
          cat > ansible/inventory.yml << EOF
          all:
            children:
              preview_server:
                hosts:
                  preview:
                    ansible_host: ${{ secrets.ANSIBLE_HOST }}
                    ansible_user: ${{ secrets.ANSIBLE_USER }}
                    ansible_ssh_private_key_file: ~/.ssh/preview
                    ansible_command_timeout: 900
                    ansible_port: ${{ secrets.ANSIBLE_PORT }}
          EOF

      - name: Set PR ID for workflow dispatch or PR event
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR_ID=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "PR_ID=${{ github.event.inputs.pr_id }}" >> $GITHUB_ENV
          fi

      - name: Set Branch Variables
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            FRONTEND_BRANCH="${{ github.head_ref }}"

            backend_branch=$(echo "${{ github.event.pull_request.body }}" | grep -oiE 'backend:\s*[A-Za-z0-9._/-]+' | awk '{print $2}')
            if [ -z "$backend_branch" ]; then
              backend_branch="main"
            fi

          else
            FRONTEND_BRANCH="${{ github.event.inputs.frontend_branch }}"
            backend_branch="${{ github.event.inputs.backend_branch }}"
          fi

          echo "FRONTEND_BRANCH=$FRONTEND_BRANCH" >> $GITHUB_ENV
          echo "BACKEND_BRANCH=$backend_branch" >> $GITHUB_ENV

          echo "📌 Branches to checkout:"
          echo "Frontend branch: $FRONTEND_BRANCH"
          echo "Backend branch: $backend_branch"

      - name: Create deployment status
        uses: actions/github-script@v7
        id: deployment
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: `pr-${{ env.PR_ID }}`,
              description: `Deploy PR #${{ env.PR_ID }} preview`,
              auto_merge: false,
              required_contexts: []
            });

            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'in_progress',
              description: 'Deployment in progress',
              environment_url: `https://pr-${{ env.PR_ID }}.${{ vars.TRAEFIK_DOMAIN }}`
            });

            return deployment.data.id;

      - name: Run Ansible playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventory.yml deploy-preview.yml \
            --extra-vars "pr_id=${{ env.PR_ID }}" \
            --extra-vars "traefik_domain=${{ vars.TRAEFIK_DOMAIN }}" \
            --extra-vars "main_repo=${{ vars.MAIN_REPO || 'https://github.com/ts-factory/bublik-docker' }}" \
            --extra-vars "main_branch=${{ vars.MAIN_BRANCH || 'main' }}" \
            --extra-vars "frontend_repo=${{ vars.FRONTEND_REPO || 'https://github.com/ts-factory/bublik-ui.git' }}" \
            --extra-vars "frontend_branch=${{ env.FRONTEND_BRANCH }}" \
            --extra-vars "backend_repo=${{ vars.BACKEND_REPO || 'https://github.com/ts-factory/bublik.git' }}" \
            --extra-vars "backend_branch=${{ env.BACKEND_BRANCH }}" \
            --extra-vars "django_superuser_email=${{ secrets.DJANGO_SUPERUSER_EMAIL }}" \
            --extra-vars "django_superuser_password=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" \
            -v

      - name: Update deployment status - Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'success',
              description: 'Deployment successful',
              environment_url: `https://pr-${{ env.PR_ID }}.${{ vars.TRAEFIK_DOMAIN }}`
            });

      - name: Update deployment status - Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'failure',
              description: 'Deployment failed',
              environment_url: `https://pr-${{ env.PR_ID }}.${{ vars.TRAEFIK_DOMAIN }}`
            });

      - name: Deployment result comment
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: deploy-preview
          message: |
            ${{ job.status == 'success' && '✅ **Deployment successful!**' || '❌ **Deployment failed!**' }}

            ### Deployment Summary for PR #${{ env.PR_ID }}

            **Preview URL:** [https://pr-${{ env.PR_ID }}.${{ vars.TRAEFIK_DOMAIN }}](https://pr-${{ env.PR_ID }}.${{ vars.TRAEFIK_DOMAIN }})
            **Frontend branch:** `${{ env.FRONTEND_BRANCH }}`
            **Backend branch:** `${{ env.BACKEND_BRANCH }}`
            **Environment:** `pr-${{ env.PR_ID }}`

            ---
            _This comment is automatically generated by the deployment workflow._
